/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    // Time Complexity - O(n), Space Complexity - O(1)
    const letterCountInS = {};
    const letterCountInT = {};

    for (let ch of s) {
        if (letterCountInS[ch]) {
            letterCountInS[ch] += 1;
        } else {
            letterCountInS[ch] = 1;
        }
    }

    for (let ch of t) {
        if (letterCountInT[ch]) {
            letterCountInT[ch] += 1;
        } else {
            letterCountInT[ch] = 1;
        }
    }

    for (let ch of Object.keys(letterCountInT)) {
        if (!letterCountInS[ch]) return ch;
        if (letterCountInT[ch] > letterCountInS[ch]) return ch;
    }
};

console.log(findTheDifference("abcd", "abcde")); // "e"
console.log(findTheDifference("", "y")); // "y"